baseurl = "https://my-awesome.site"

[webmentions]
newDir = "testdata/staging"         # the directory where newly created site is
oldDir = "testdata/prod/"           # the directory where old (or current) site is
webmentionsFile = "mentions.json"   # the file to store pending webmentions in
  
## pages that should not be considered as webmention sources
excludeSources = [
  "/tags/*",                    # only trailing * are supported at the moment
  "/posts",                     # this only excludes /posts/index.html, not /posts/somepost/
  "/",                          # same as "/index.html"
]

## addresses that we don't want to send webmentions to
excludeDestinations = [
  "https://my-awesome.site",    # this still allows mentioning pages other than the homepage
  "mailto:",                    # schemes are accepted
  "/tags"                       # relative paths for our own site include all the pages under that directory
]

[params]
websubHub = ["https://pubsubhubbub.superfeedr.com/","https://thehub.pubsub"]   # if this is present, will look for changes in XML files and notify the hub(s)
feedFiles = ["index.xml", "other.xml"]
