name: codecov
on: [push]
jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: vet
        run: |
          go vet ./...
      - name: generate report
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: upload coverage report
        uses: codecov/codecov-action@v1
