name: build
on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  pre_release:
    runs-on: ubuntu-latest
    env:
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: |
            ${{ runner.os }}-build-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/go.mod') }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install nekr0z/changelog
        run: |
          go install github.com/nekr0z/changelog/cmd/changelog@latest

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: install fpm
        run: gem install fpm

      - name: build packages
        run: |
          mkdir release
          changelog -n "Evgeny Kuznetsov" -e "evgeny@kuznetsov.md" -p "static-webmentions" CHANGELOG.md
          bash <(VER=$(go generate); for ARCH in amd64 386 arm arm64; do GOARCH=$ARCH CGO_ENABLED=0 go build -ldflags "-s -w -buildid= -X main.version=$VER"; tar -czf release/static-webmentions-$VER-linux-$ARCH.tar.gz static-webmentions LICENSE README.md CHANGELOG.md SOURCE.txt; fpm -t deb -s dir -a $ARCH -n static-webmentions -v ${VER%+*} -m "Evgeny Kuznetsov <evgeny@kuznetsov.md>" --deb-changelog debian.changelog --license GPL-3 --deb-priority optional --url https://github.com/nekr0z/static-webmentions --category net --vendor "Evgeny Kuznetsov <evgeny@kuznetsov.md>" --description "A tool to send webmentions from a static website." LICENSE=/usr/share/doc/static-webmentions/ README.md=/usr/share/doc/static-webmentions/ SOURCE.txt=/usr/share/doc/static-webmentions static-webmentions=/usr/bin/ >/dev/null; mv *.deb release/; done)
          cd release
          fpm -s deb -t deb -a i386 *386.deb
          rm *_386.deb
          fpm -s deb -t deb -a armel *arm.deb
          rm *arm.deb
      - name: release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "release/*"
